### ISSUE TITLE
手机日间模式 app设置夜间模式 然后开屏会有白屏 

### ISSUE THREAD

**Issue by pangyu646182805** [a-liYa/AndroidUiMode#2]
手机日间模式 app设置夜间模式 然后开屏会有白屏 会有闪一下的效果

**Comment by a-liYa** [comment]
给启动页Activity 设置 `<item name="android:windowBackground">@android:color/transparent</item>` 可以解决这个问题，具体配置看这笔commit https://github.com/a-liYa/AndroidUiMode/commit/4a9b2f3b6e28d7511b00f1531e476458eb03f106
